version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-otw958a&c)_-ri0@q4zy=oq18zx%0c^zypz0re$(rxdi@br8%p"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:15
    volumes:
      - postgres_bookstore_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_bookstore_data:
